development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: yelp_db_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: yelp_db_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: yelp_db_production
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
