settings:
  address               : "smtp.gmail.com"
  port                  : 587
  domain                : "gmail.com"
  username              : "se3.roland@gmail.com"
  password              : "gmT35TP455**"
  authentication        : "plain"
  enable_starttls_auto  : true
  default_url           :
    host                  : "localhost:3000"
    protocol              : "https"
  development_email    : "se3.roland@gmail.com" # all emails will be sent to this address when in development environment
