settings:
  account_admin:
    username: admin
    password: adm123
    token_expiry: 86400
  switch:
    google_analytics: false
    billing: false
  default_locale: en
  theme:
    sidebar: "#373737"
    primary: "#DD0038"
    primary_gradient: "#C3002F"
  app_version: 1.0.0
  app_name: Frozen Proton
  installation_environment: development
  support_url: https://www.support.com
  support_email: roland.rose888@yahoo.com
  noreply_email: no-reply@frozenproton.com
  notification_email: notifications@frozenproton.com
  billing_provider: authorize.net
  billing_email: billing@frozenproton.com
  # Set token_expiry to expire in 24 hours(86400sec).
